package database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zxyoyo.apk.ji.accounting.source.AccountBean;
import com.zxyoyo.apk.ji.login.source.UserBean;
import com.zxyoyo.apk.ji.accounting.source.GoodsTypeBean;

import database.AccountBeanDao;
import database.UserBeanDao;
import database.GoodsTypeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig goodsTypeBeanDaoConfig;

    private final AccountBeanDao accountBeanDao;
    private final UserBeanDao userBeanDao;
    private final GoodsTypeBeanDao goodsTypeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountBeanDaoConfig = daoConfigMap.get(AccountBeanDao.class).clone();
        accountBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        goodsTypeBeanDaoConfig = daoConfigMap.get(GoodsTypeBeanDao.class).clone();
        goodsTypeBeanDaoConfig.initIdentityScope(type);

        accountBeanDao = new AccountBeanDao(accountBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        goodsTypeBeanDao = new GoodsTypeBeanDao(goodsTypeBeanDaoConfig, this);

        registerDao(AccountBean.class, accountBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(GoodsTypeBean.class, goodsTypeBeanDao);
    }
    
    public void clear() {
        accountBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        goodsTypeBeanDaoConfig.clearIdentityScope();
    }

    public AccountBeanDao getAccountBeanDao() {
        return accountBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public GoodsTypeBeanDao getGoodsTypeBeanDao() {
        return goodsTypeBeanDao;
    }

}
